# 回归测试配置文件
# Test Configuration for Daily Regression


# 测试套件定义
test_suites:
  detection:
    name: "DetectionTestSuite.*"
    description: "目标检测测试"
  classification:
    name: "ClassificationTestSuite.*"
    description: "分类模型测试"
  face_attribute:
    name: "AttributesTestSuite.*"
    description: "人脸属性测试"
  keypoint:
    name: "KeypointTestSuite.*"
    description: "关键点检测测试"
  feature:
    name: "FeatureExtraTestSuite.*"
    description: "特征提取测试"
  segmentation:
    name: "SegmentationTestSuite.*"
    description: "分割模型测试"
  ocr:
    name: "OcrTestSuite.*"
    description: "文字识别测试"
  sot:
    name: "SotTestSuite.*"
    description: "SOT模型测试"

# 测试文件配置 - 按平台分类
test_files:
  # 通用测试（所有平台）
  common:
    detection:
      - "mbv2_det_person_256_448_INT8.json"
      - "mbv2_det_person_512_896_INT8.json"
      - "mbv2_det_person_256_384_INT8.json"
      - "mbv2_det_person_896_896_INT8.json"
      - "ppyoloe_det_coco80_640_640_INT8.json"
      - "yolov10n_det_coco80_640_640_INT8.json"
      - "yolov6n_det_coco80_640_640_INT8.json"
      - "yolov6s_det_coco80_640_640_INT8.json"
      - "yolov8n_det_coco80_640_640_INT8.json"
      - "yolov8n_det_face_head_person_pet_384_640_INT8.json"
      - "yolov8n_det_fire_smoke_384_640_INT8.json"
      - "yolov8n_det_hand_face_person_384_640_INT8.json"
      - "yolov8n_det_head_hardhat_576_960_INT8.json"
      - "yolov8n_det_ir_person_384_640_INT8.json"
      - "yolov8n_det_ir_person_mbv2_384_640_INT8.json"
      - "yolov8n_det_license_plate_384_640_INT8.json"
      - "yolov8n_det_monitor_person_256_448_INT8.json"
      - "yolov8n_det_overlook_person_256_448_INT8.json"
      - "yolov8n_det_person_vehicle_384_640_INT8.json"
      - "yolov8n_det_person_vehicle_mv2_035_384_640_INT8.json"
      - "yolov8n_det_pet_person_035_384_640_INT8.json"
      - "yolov8n_det_pet_person_384_640_INT8.json"
      - "yolov8n_det_traffic_light_384_640_INT8.json"
      - "yolov8s_det_coco80_640_640_INT8.json"
      - "yolov8n_det_head_shoulder_384_640_INT8.json"
      - "yolov8n_det_head_person_384_640_INT8.json"
      - "yolov8n_det_fire_384_640_INT8.json"
      - "scrfd_det_face_432_768_INT8.json"
      - "yolov8n_det_hand_384_640_INT8.json"
      - "yolov8n_det_hand_mv3_384_640_INT8.json"
      - "yolov8n_det_bicycle_motor_ebicycle_384_640_INT8.json"
      - "yolov8n_det_bicycle_motor_ebicycle_mbv2_384_640_INT8.json"
      - "yolov5m_det_coco80_640_640_INT8.json"
      - "yolov5s_det_coco80_640_640_INT8.json"
      - "yolov7_tiny_det_coco80_640_640_INT8.json"
    
    classification:
      - "cls_hand_gesture_128_128_INT8.json"
      - "cls_rgbliveness_256_256_INT8.json"
      - "cls_sound_babay_cry_188_40_INT8.json"
      - "cls_sound_nihaoshiyun_126_40_INT8.json"
      - "cls_sound_xiaoaixiaoai_126_40_INT8.json"
      - "cls_keypoint_hand_gesture_1_42_INT8.json"
    
    face_attribute:
      - "cls_attribute_gender_age_glass_mask_112_112_INT8.json"
      - "cls_attribute_gender_age_glass_112_112_INT8.json"
      - "cls_attribute_gender_age_glass_emotion_112_112_INT8.json"
    
    keypoint:
      - "keypoint_face_v2_64_64_INT8.json"
      - "keypoint_hand_128_128_INT8.json"
      - "keypoint_license_plate_64_128_INT8.json"
      - "keypoint_simcc_person17_256_192_INT8.json"
      - "keypoint_yolov8pose_person17_384_640_INT8.json"
      - "lstr_det_lane_360_640_MIX.json"
    
    feature:
      - "feature_cviface_112_112_INT8.json"
    
    segmentation:
      - "yolov8n_seg_coco80_640_640_INT8.json"
      - "topformer_seg_person_face_vehicle_384_640_INT8.json"
    
    ocr:
        - "recognition_license_plate_24_96_MIX.json"

    sot:
      - "tracking_feartrack_128_128_256_256_INT8.json"

  # 特定平台排除的测试（由于 tpu-milr bug）
  exclude:
    CV184X:
      detection:
        - "yolov5m_det_coco80_640_640_INT8.json"
        - "yolov5s_det_coco80_640_640_INT8.json"
        - "yolov7_tiny_det_coco80_640_640_INT8.json"
    CV186X:
      detection:
        - "yolov5m_det_coco80_640_640_INT8.json"
        - "yolov5s_det_coco80_640_640_INT8.json"
        - "yolov7_tiny_det_coco80_640_640_INT8.json"
    BM1688:
      detection:
        - "yolov5s_det_coco80_640_640_INT8.json"
        - "yolov7_tiny_det_coco80_640_640_INT8.json"
        - "yolov8n_det_bicycle_motor_ebicycle_mbv2_384_640_INT8.json"
        - "yolov8n_det_bicycle_motor_ebicycle_384_640_INT8.json"
        - "yolov8n_det_head_person_384_640_INT8.json"
        - "mbv2_det_person_256_384_INT8.json"
        - "yolov8n_det_face_head_person_pet_384_640_INT8.json"
        - "yolov8n_det_ir_person_mbv2_384_640_INT8.json"
      feature:
        - "feature_cviface_112_112_INT8.json"
      face_attribute:
        - "cls_attribute_gender_age_glass_mask_112_112_INT8.json"
        - "cls_attribute_gender_age_glass_112_112_INT8.json"
        - "cls_attribute_gender_age_glass_emotion_112_112_INT8.json"
      classification:
        - "cls_keypoint_hand_gesture_1_42_INT8.json"
      keypoint:
        - "keypoint_face_v2_64_64_INT8.json"
      segmentation:
        - "yolov8n_seg_coco80_640_640_INT8.json"
      ocr:
        - "recognition_license_plate_24_96_MIX.json"
    BM1684X:
      detection:
        - "yolov5s_det_coco80_640_640_INT8.json"
        - "yolov7_tiny_det_coco80_640_640_INT8.json"
        - "yolov8n_det_bicycle_motor_ebicycle_mbv2_384_640_INT8.json"
        - "yolov8n_det_bicycle_motor_ebicycle_384_640_INT8.json"
        - "yolov8n_det_head_person_384_640_INT8.json"
        - "mbv2_det_person_256_384_INT8.json"
        - "yolov8n_det_face_head_person_pet_384_640_INT8.json"
        - "yolov8n_det_ir_person_mbv2_384_640_INT8.json"
      feature:
        - "feature_cviface_112_112_INT8.json"
      face_attribute:
        - "cls_attribute_gender_age_glass_mask_112_112_INT8.json"
        - "cls_attribute_gender_age_glass_112_112_INT8.json"
        - "cls_attribute_gender_age_glass_emotion_112_112_INT8.json"
      classification:
        - "cls_keypoint_hand_gesture_1_42_INT8.json"
      keypoint:
        - "keypoint_face_v2_64_64_INT8.json"
      segmentation:
        - "yolov8n_seg_coco80_640_640_INT8.json"
      ocr:
        - "recognition_license_plate_24_96_MIX.json"



